import { ExportControls } from './ExportControls';
import { useState } from 'react';
import { useStore } from '../store';
import { projectStorage, type ProjectSummary } from '../storage/ProjectStorage';
import { useT } from '../i18n';
export function ProjectMenu() {
  const t = useT(); const project = useStore(s => s.project); const [open, setOpen] = useState(false), [name, setName] = useState(''), [recent, setRecent] = useState<ProjectSummary[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function perform(fn: () => Promise<unknown>) { setBusy(true); setError(''); try { await fn(); setOpen(false); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  return <><button className="project-menu-button" onClick={() => { setName(project.name); setOpen(true); setError(''); void projectStorage.recent().then(setRecent).catch(e => setError(String(e))); }}>{t('projectMenu')} · {project.name}</button>{open && <div className="modal-backdrop"><section className="compact-dialog" role="dialog" aria-modal="true" aria-label={t('projectMenu')}><header><h2>{t('projectMenu')}</h2><button disabled={busy} onClick={() => setOpen(false)}>{t('close')}</button></header><label>{t('projectName')}<input aria-label={t('projectName')} value={name} onChange={e => setName(e.target.value)} /></label><div className="project-actions"><button disabled={busy} onClick={() => void perform(() => useStore.getState().newProject(name))}>{t('newProject')}</button><button disabled={busy} onClick={() => void perform(async () => { const loaded = await projectStorage.pickProject(); if (loaded) await useStore.getState().openProject(loaded); })}>{t('openProject')}</button><button disabled={busy} onClick={() => void perform(() => useStore.getState().saveProject())}>{t('saveProject')}</button><button disabled={busy} onClick={() => void perform(() => useStore.getState().saveAs(name))}>{t('saveAs')}</button></div><details><summary>{t('fileExport')}</summary>{project.shots.filter(s=>s.id===project.activeShotId).map(shot=><ExportControls key={shot.id} shot={shot} />)}</details><h3>{t('recentProjects')}</h3><div className="recent-projects">{recent.map(p => <button key={p.id} disabled={busy || p.id === project.id} onClick={() => void perform(() => useStore.getState().openRecent(p.id))}><span>{p.name}</span><small>{p.updatedAt ? new Date(p.updatedAt).toLocaleString() : ''}</small></button>)}</div>{busy && <p>{t('projectBusy')}</p>}{error && <p className="error-text" role="alert">{error}</p>}</section></div>}</>;
}
