// Uses an existing Playwright installation; adds no application dependency.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  fs.mkdirSync('.verification', { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto(process.env.APP_URL || 'http://127.0.0.1:5173');
  await page.getByRole('heading', { name: 'Spatial editor' }).count();
  await page.getByRole('button', { name: 'Select SHOT 001', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelectorAll('canvas').length === 2);
  await page.waitForTimeout(1800);
  await page.screenshot({ path: '.verification/initial.png' });
  const add = async type => { await page.getByRole('button', { name: 'Add object' }).click(); await page.locator('.add-menu').getByRole('button', { name: type, exact: false }).click(); };
  await page.getByLabel('Shot title', { exact: true }).fill('The signal');
  await page.getByLabel('Shot description', { exact: true }).fill('Leo discovers a beacon in an empty clearing.');
  await add('Character');
  await page.getByLabel('Object name', { exact: true }).fill('Leo');
  await page.getByLabel('Facing direction').selectOption('90');
  await add('Prop');
  await page.getByLabel('Object name', { exact: true }).fill('Emergency Beacon');
  await page.getByLabel('Semantic name').fill('Emergency Beacon');
  await page.getByLabel('Position X').fill('1.2');
  await page.getByLabel('Position Z').fill('0');
  await page.getByLabel('Rotation Y').fill('-90');
  await page.getByRole('button', { name: 'Medium', exact: true }).click();
  await page.getByLabel('Camera FOV degrees').fill('48');
  await page.getByRole('button', { name: 'Golden Spiral', exact: true }).click();
  await page.getByRole('button', { name: 'Center Cross', exact: true }).click();
  await page.getByRole('button', { name: 'Safe Frame', exact: true }).click();
  assert.equal(await page.locator('[data-overlay]').count(), 4);
  await page.getByRole('button', { name: 'Generate Spatial Description', exact: true }).click();
  const description = await page.getByLabel('Generated spatial description').inputValue();
  assert.match(description, /Leo/); assert.match(description, /Emergency Beacon/); assert.match(description, /1.2 meters/);
  await page.getByRole('button', { name: 'Copy', exact: true }).click();
  await page.getByRole('button', { name: 'Copied', exact: true }).waitFor();
  assert.equal((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, '\n'), description);
  const previewBefore = await page.getByTestId('camera-preview').screenshot();
  await page.getByLabel('Position X').fill('5');
  await page.waitForTimeout(500);
  const previewAfter = await page.getByTestId('camera-preview').screenshot();
  assert(!previewBefore.equals(previewAfter), 'Moving camera must update preview pixels');
  assert.notEqual(await page.getByLabel('Generated spatial description').inputValue(), description, 'Scene edits update the generated description live');
  await page.getByRole('button', { name: 'Medium', exact: true }).click();
  await page.getByRole('button', { name: 'Generate Spatial Description', exact: true }).click();
  const imagePath = path.resolve('.verification/reference.png');
  await page.getByTestId('camera-preview').screenshot({ path: imagePath });
  await page.getByLabel('Import storyboard image', { exact: true }).setInputFiles(imagePath);
  await page.getByRole('img', { name: 'Storyboard reference', exact: true }).waitFor();
  await page.getByLabel('Shot status', { exact: true }).selectOption('Approved');
  await page.getByRole('status').filter({ hasText: 'All changes saved' }).waitFor();
  const saved = await page.evaluate(async () => {
    const { useStore } = await import(performance.getEntriesByType('resource').find(e => e.name.includes('/src/store.ts'))?.name || '/src/store.ts');
    return useStore.getState().project;
  });
  await page.reload();
  await page.getByRole('status').filter({ hasText: 'All changes saved' }).waitFor();
  const restored = await page.evaluate(async () => (await import(performance.getEntriesByType('resource').find(e => e.name.includes('/src/store.ts'))?.name || '/src/store.ts')).useStore.getState().project);
  assert.deepEqual(restored, saved, 'All shot properties, transforms, image and overlays persist');
  await page.getByRole('img', { name: 'Storyboard reference', exact: true }).waitFor();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: '.verification/workflow.png' });

  // TransformControls drag: locate rendered gizmo using its projected world axis.
  await page.locator('.scene-list').getByRole('button', { name: 'Leo', exact: true }).click();
  await page.getByRole('button', { name: 'Move', exact: true }).click();
  const dragAxis = async (name, field, mode = 'Move') => {
    await page.locator('.scene-list').getByRole('button', { name, exact: true }).click();
    await page.getByRole('button', { name: mode, exact: true }).click();
    await page.waitForTimeout(150);
    const before = await page.getByLabel(field, { exact: true }).inputValue();
    const points = await page.evaluate(async () => {
      const { _roots } = await import('/node_modules/.vite/deps/@react-three_fiber.js');
      const { Vector3 } = await import('/node_modules/.vite/deps/three.js');
      const canvas = document.querySelector('.editor-canvas canvas');
      const state = _roots.get(canvas).store.getState();
      let controls;
      state.scene.traverse(o => { if (o.isTransformControls || o.type === 'TransformControls') controls = o; });
      if (!controls) throw new Error('TransformControls not found');
      const gizmo = controls.children.find(o => o.type === 'TransformControlsGizmo');
      const handle = gizmo.gizmo[controls.mode].children.find(o => o.name === 'X' && o.isMesh && o.visible);
      handle.geometry.computeBoundingBox();
      const start = handle.geometry.boundingBox.getCenter(new Vector3()).applyMatrix4(handle.matrixWorld).project(state.camera);
      const box = canvas.getBoundingClientRect();
      return { x: box.x + (start.x + 1) * box.width / 2, y: box.y + (1 - start.y) * box.height / 2 };
    });
    await page.mouse.move(points.x, points.y);
    await page.mouse.down();
    await page.mouse.move(points.x + 45, points.y + 12, { steps: 12 });
    await page.mouse.up();
    const after = await page.getByLabel(field, { exact: true }).inputValue();
    assert.notEqual(after, before, `${name} ${mode} gizmo must change ${field}`);
    await page.keyboard.press('Control+z');
    assert.equal(await page.getByLabel(field, { exact: true }).inputValue(), before, 'One undo restores the entire drag');
    await page.keyboard.press('Control+Shift+z');
    assert.equal(await page.getByLabel(field, { exact: true }).inputValue(), after, 'Redo restores the entire drag');
  };
  await dragAxis('Leo', 'Position X');
  await dragAxis('Emergency Beacon', 'Position X');
  await dragAxis('Storyboard Camera', 'Position X');
  await dragAxis('Leo', 'Scale X', 'Scale');
  await page.locator('.scene-list').getByRole('button', { name: 'Storyboard Camera', exact: true }).click();
  const beforeRotation = await page.getByTestId('camera-preview').screenshot();
  await page.getByLabel('Rotation Y', { exact: true }).fill('65');
  await page.waitForTimeout(200);
  assert(!(await page.getByTestId('camera-preview').screenshot()).equals(beforeRotation), 'Camera rotation updates preview');
  await page.getByRole('button', { name: 'Rotate', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Rotate', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.screenshot({ path: '.verification/selected.png' });

  // Add, edit and remove every remaining primitive; verify shot isolation.
  await add('Cube'); await page.getByLabel('Scale X').fill('2'); await page.getByLabel('Rotation Z').fill('25');
  await page.getByRole('button', { name: 'Delete object', exact: true }).click();
  await add('Plane'); await page.getByRole('button', { name: 'Delete object', exact: true }).click();
  await page.getByRole('button', { name: 'New shot', exact: true }).first().click();
  await page.getByRole('button', { name: 'Select SHOT 002', exact: true }).waitFor();
  assert.equal(await page.locator('.scene-list .scene-select').count(), 1);
  await page.getByRole('button', { name: 'Delete object', exact: true }).click();
  await page.getByText('Add a Camera to see your composition.').waitFor();
  await add('Camera');
  await page.getByLabel('Object name', { exact: true }).fill('Replacement Camera');
  await page.getByRole('button', { name: 'Select SHOT 001', exact: true }).click();
  assert.equal(await page.locator('.scene-list .scene-select').count(), 3);
  assert.equal(await page.getByLabel('Shot title', { exact: true }).inputValue(), 'The signal');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete SHOT 002', exact: true }).click();
  assert.equal(await page.locator('.shot-card').count(), 1);
  await page.getByRole('button', { name: 'Remove storyboard image', exact: true }).click();
  assert.equal(await page.getByRole('img', { name: 'Storyboard reference', exact: true }).count(), 0);
  assert.deepEqual(errors, [], 'No browser runtime or console errors');
  console.log('PASS: character/prop/camera gizmo dragging, gizmo scaling, camera rotation and pixel updates, overlays, description, clipboard, image import/removal, IndexedDB reload, object deletion, shot isolation and deletion.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });

