const { chromium }=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.APP_URL||'http://127.0.0.1:5173');await page.getByRole('status').filter({hasText:'All changes saved'}).waitFor();
 const migration=await page.evaluate(async()=>{
  const s=(await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/store.ts'))?.name||'/src/store.ts')).useStore.getState();
  const legacy=structuredClone(s.project);delete legacy.schemaVersion;delete legacy.name;delete legacy.updatedAt;for(const shot of legacy.shots){delete shot.plan;delete shot.annotations;delete shot.primarySubjectId;delete shot.constraints;delete shot.negativeConstraints;for(const o of shot.objects){delete o.frontYaw;delete o.frontLabel;}}
  await new Promise((resolve,reject)=>{const req=indexedDB.open('StoryboardSpatialDirector');req.onsuccess=()=>{const db=req.result;const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(legacy);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=reject;};});return legacy;
 });
 await page.reload();await page.getByRole('status').filter({hasText:'All changes saved'}).waitFor();
 const restored=await page.evaluate(async()=>{const s=(await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/store.ts'))?.name||'/src/store.ts')).useStore.getState();const backups=await new Promise(resolve=>{const req=indexedDB.open('StoryboardSpatialDirector');req.onsuccess=()=>{const db=req.result;const tx=db.transaction('backups');const r=tx.objectStore('backups').getAll();r.onsuccess=()=>resolve(r.result);tx.oncomplete=()=>db.close();};});return {project:s.project,backups};});
 assert.equal(restored.project.schemaVersion,3);assert.equal(restored.project.shots[0].objects[0].id,migration.shots[0].objects[0].id);assert.deepEqual(restored.project.shots[0].objects[0].position,migration.shots[0].objects[0].position);assert.deepEqual(restored.project.shots[0].plan.sketches,[]);assert(restored.backups.some(b=>JSON.stringify(b.data)===JSON.stringify(migration)));
 await page.evaluate(async()=>{const s=(await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/store.ts'))?.name||'/src/store.ts')).useStore.getState();const bad={...s.project,schemaVersion:999,name:'KEEP THIS DATA'};await new Promise(resolve=>{const req=indexedDB.open('StoryboardSpatialDirector');req.onsuccess=()=>{const db=req.result;const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(bad);tx.oncomplete=()=>{db.close();resolve();};};});});
 await page.reload();await page.getByRole('alert').filter({hasText:/newer version/}).waitFor();
 const recovered=await page.evaluate(async()=>{const {useStore}=await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/store.ts'))?.name||'/src/store.ts');const wasRecovery=useStore.getState().recovery;useStore.getState().addShot();await useStore.getState().newProject('Safe independent project');const current=useStore.getState().project;const old=await new Promise(resolve=>{const req=indexedDB.open('StoryboardSpatialDirector');req.onsuccess=()=>{const db=req.result;const tx=db.transaction('projects');const r=tx.objectStore('projects').get('local-project');r.onsuccess=()=>resolve(r.result);tx.oncomplete=()=>db.close();};});return {wasRecovery,current,old};});
 assert(recovered.wasRecovery);assert.notEqual(recovered.current.id,'local-project');assert.equal(recovered.old.schemaVersion,999);assert.equal(recovered.old.name,'KEEP THIS DATA');
 // Invalid project contents must fail validation before any switch.
 const validation=await page.evaluate(async()=>{const {migrateProject}=await import('/src/storage/ProjectStorage.ts');const s=(await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/store.ts'))?.name||'/src/store.ts')).useStore.getState();const p=s.project;const samples=[];for(const change of [p=>p.shots[0].objects[0].position=[NaN,0,0],p=>p.shots[0].objects.push({...p.shots[0].objects[0]}),p=>p.shots[0].objects[0].type='Unsupported',p=>p.shots[0].objects[0].locked='yes',p=>p.shots[0].plan.sketches=[{id:'bad',tool:'script',points:[]}],p=>p.shots[0].image='https://example.com/unsafe.png']){const candidate=structuredClone(p);change(candidate);try{migrateProject(candidate);samples.push(false);}catch{samples.push(true);}}return samples;});assert(validation.every(Boolean));
 // A simulated failed IndexedDB write cannot be hidden by switching projects.
 const failure=await page.evaluate(async()=>{const mod=await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/storage/ProjectStorage.ts'))?.name||'/src/storage/ProjectStorage.ts');const {useStore}=await import(performance.getEntriesByType('resource').find(e=>e.name.includes('/src/store.ts'))?.name||'/src/store.ts');const storage=mod.projectStorage,save=storage.save.bind(storage);storage.save=async()=>{throw new Error('Simulated quota failure');};useStore.getState().updateShot({title:'Unsaved work'});await new Promise(r=>setTimeout(r,100));const before=useStore.getState().project.id;let rejected=false;try{await useStore.getState().newProject('Must not switch');}catch{rejected=true;}const same=useStore.getState().project.id===before;storage.save=save;useStore.getState().retrySave();return {rejected,same};});assert(failure.rejected);assert(failure.same);await page.getByRole('status').filter({hasText:'All changes saved'}).waitFor();
 assert.deepEqual(errors,[]);console.log('PASS storage: untouched V0.2 backup + migration, unsupported startup records retained, recovery blocks writes, new recovery workspace is independent, malformed scenes rejected, failed autosave blocks destructive switching and retry succeeds.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
