import { useSettings, type Language } from './settings';

// All interface copy is defined here. Object names and authored shot text are user data.
const messages = {
  brand: ['Storyboard', '分镜'], director: ['SPATIAL DIRECTOR', '空间调度'], fullBrand: ['STORYBOARD SPATIAL DIRECTOR', '分镜空间调度工具'],
  language: ['Language', '语言'], english: ['English', 'English'], chinese: ['简体中文', '简体中文'],
  shotList: ['Shot list', '镜头列表'], sequence: ['YOUR SEQUENCE', '分镜序列'], local: ['LOCAL', '本地'], localProject: ['LOCAL PROJECT', '本地项目'], untitledSequence: ['Untitled sequence', '未命名序列'],
  shot: ['SHOT {n}', '镜头 {n}'], selectShot: ['Select SHOT {n}', '选择镜头 {n}'], deleteShot: ['Delete SHOT {n}', '删除镜头 {n}'], confirmDelete: ['Delete SHOT {n} and its scene? You can undo this action.', '删除镜头 {n} 及其场景？此操作可撤销。'],
  noStoryboard: ['No storyboard yet', '尚未导入分镜图'], storyboardFor: ['Storyboard for {name}', '{name} 的分镜图'], untitledShot: ['Untitled shot', '未命名镜头'], addMoment: ['Add a moment to your sequence.', '为分镜序列添加一个片刻。'],
  Draft: ['Draft', '草稿'], Approved: ['Approved', '已确认'], newShot: ['New shot', '新建镜头'], duplicateShot: ['Duplicate Shot', '复制镜头'], copyPrevious: ['Copy Scene From Previous Shot', '从上一镜头复制场景'], copySuffix: ['{name} — copy', '{name} — 副本'],
  confirmCopy: ['Replace this shot’s scene with the previous shot’s scene? You can undo this action.', '用上一镜头的场景替换当前场景？此操作可撤销。'],
  tagline: ['Every frame starts with a little direction.', '每一帧，从空间调度开始。'], versionTag: ['SPATIAL BLOCKING · MVP 02', '空间调度 · MVP 02'],
  reference: ['Storyboard reference', '分镜参考图'], removeImage: ['Remove storyboard image', '移除分镜图'], replaceImage: ['Replace image', '替换图片'], importImage: ['Import storyboard image', '导入分镜图'], imageFormats: ['PNG, JPG, WebP or GIF · up to 10 MB', 'PNG、JPG、WebP 或 GIF · 最大 10 MB'],
  imageTypeError: ['Choose a PNG, JPG, WebP or GIF image.', '请选择 PNG、JPG、WebP 或 GIF 图片。'], imageSizeError: ['Please choose an image smaller than 10 MB.', '请选择小于 10 MB 的图片。'], imageReadError: ['This image could not be opened. Try another file.', '无法打开此图片，请尝试其他文件。'],
  spatialDescription: ['Spatial description', '空间关系描述'], sceneWords: ['SCENE → WORDS', '场景 → 文字'], compositionNotes: ['COMPOSITION NOTES', '构图说明'], copy: ['Copy', '复制'], copied: ['Copied', '已复制'], manualCopy: ['Press Ctrl+C', '请按 Ctrl+C'], generatedDescription: ['Generated spatial description', '生成的空间描述'],
  descriptionPlaceholder: ['Your blocking, put into words.\n\nPlace your subjects and frame the shot, then generate a description of the scene.', '将空间调度转化为文字。\n\n摆放主体并调整构图，然后生成场景的空间关系描述。'], generate: ['Generate Spatial Description', '生成空间描述'], generatedLocally: ['Generated locally from positions and angles.', '根据位置与角度在本地生成。'],
  thirds: ['Rule of Thirds', '三分构图线'], cross: ['Center Cross', '中心十字线'], safe: ['Safe Frame', '安全框'], spiral: ['Golden Spiral', '黄金螺旋'], guides: ['GUIDES', '构图辅助线'], compositionGuides: ['Composition guides', '构图辅助线'],
  loading: ['Opening your workspace…', '正在打开工作区…'], saved: ['All changes saved', '所有更改已保存'], saving: ['Saving…', '正在保存…'], storageUnavailable: ['Storage unavailable', '存储不可用'], storageError: ['Local storage failed: {detail}', '本地存储失败：{detail}'], retrySave: ['Retry save', '重试保存'],
  blockFrame: ['BLOCK THE SCENE. FIND THE FRAME.', '调度空间，确定构图。'], spatialEditor: ['Spatial editor', '空间编辑器'], select: ['Select', '选择'], translate: ['Move', '移动'], rotate: ['Rotate', '旋转'], scale: ['Scale', '缩放'], addObject: ['Add object', '添加对象'],
  Character: ['Character', '角色'], Prop: ['Prop', '道具'], Cube: ['Cube', '立方体'], Sphere: ['Sphere', '球体'], Cylinder: ['Cylinder', '圆柱体'], Capsule: ['Capsule', '胶囊体'], Cone: ['Cone', '圆锥体'], Plane: ['Plane', '平面'], Camera: ['Camera', '摄影机'], storyboardCamera: ['Storyboard Camera', '分镜摄影机'],
  scene: ['SCENE', '场景'], cameraPreview: ['Camera preview', '摄影机预览'], live: ['LIVE', '实时'], emptyHeading: ['Your next scene starts here.', '下一个镜头，从这里开始。'], emptyHelp: ['Create a shot, place your subjects, and find the frame.', '创建镜头，摆放主体，调整构图。'], createShot: ['Create a shot', '创建镜头'],
  objectCount: ['{n} objects in scene', '场景中有 {n} 个对象'], noShot: ['No shot selected', '未选择镜头'], shortcuts: ['Q Select · W Move · E Rotate · R Scale · F Frame · Del Delete · Ctrl+Z Undo', 'Q 选择 · W 移动 · E 旋转 · R 缩放 · F 聚焦 · Del 删除 · Ctrl+Z 撤销'],
  inspector: ['Inspector', '属性检查器'], object: ['OBJECT', '对象'], displayName: ['Display Name', '显示名称'], objectName: ['Object name', '对象名称'], objectType: ['Object type', '对象类型'], internalId: ['Internal ID', '内部 ID'], proxy: ['{type} proxy', '{type}替身'], activeCamera: ['Active storyboard camera', '当前分镜摄影机'],
  transform: ['TRANSFORM', '变换'], worldSpace: ['WORLD SPACE', '世界坐标'], position: ['Position', '位置'], rotation: ['Rotation', '旋转'], facing: ['Facing direction', '朝向'], facingYaw: ['Facing direction (world yaw)', '朝向（世界坐标偏航角）'],
  forward: ['Forward · +Z', '前方 · +Z'], right: ['Right · +X', '右方 · +X'], backward: ['Backward · −Z', '后方 · −Z'], left: ['Left · −X', '左方 · −X'], customAngle: ['Custom · {n}°', '自定义 · {n}°'], facingHint: ['The face marker points forward. Rotate Y for a custom direction.', '面部标记指向前方。旋转 Y 轴可自定义朝向。'],
  semanticName: ['Semantic name', '语义名称'], semanticPlaceholder: ['e.g. Emergency Beacon', '例如：紧急信标'], semanticHint: ['Legacy semantic name is preserved. Descriptions use Display Name. The dark panel marks the front.', '保留原有语义名称；空间描述使用显示名称。深色面板表示正面。'],
  lens: ['LENS', '镜头参数'], verticalFov: ['Vertical field of view', '垂直视场角'], cameraFov: ['Camera FOV', '摄影机视场角'], cameraFovDegrees: ['Camera FOV degrees', '摄影机视场角（度）'], cameraHint: ['Camera looks along its local −Z axis. Rotation is in degrees.', '摄影机沿局部 −Z 轴取景。旋转角度单位为度。'], deleteObject: ['Delete object', '删除对象'],
  shotDetails: ['SHOT DETAILS', '镜头信息'], shotTitle: ['Shot title', '镜头标题'], shortDescription: ['Short description', '简短描述'], shotDescription: ['Shot description', '镜头描述'], shotPlaceholder: ['What happens in this shot?', '这个镜头中发生了什么？'], status: ['Status', '状态'], shotStatus: ['Shot status', '镜头状态'], localWorkspace: ['LOCAL WORKSPACE', '本地工作区'],
  selectObject: ['Select an object', '选择一个对象'], selectHelp: ['Choose an object on the stage or in the scene list to adjust its properties.', '在视口或场景列表中选择对象以调整属性。'], Wide: ['Wide', '全景'], Medium: ['Medium', '中景'], Close: ['Close', '近景'], 'Low Angle': ['Low Angle', '仰拍'], 'High Angle': ['High Angle', '俯拍'],
  webglError: ['The 3D view could not start. Enable WebGL and refresh your browser.', '无法启动三维视图。请启用 WebGL 并刷新浏览器。'], perspective: ['PERSPECTIVE', '透视'], meters: ['METERS', '米'], resetView: ['Reset editor view', '重置编辑视角'], unit: ['1 unit = 1 m', '1 单位 = 1 米'], navigation: ['Alt + LMB Orbit · Alt + MMB Pan · Alt + RMB Dolly · Wheel Zoom', 'Alt + 左键 环绕 · Alt + 中键 平移 · Alt + 右键 推拉 · 滚轮 缩放'], missingCamera: ['Add a Camera to see your composition.', '添加摄影机以查看构图。'],
  showLabels: ['Show Object Labels', '显示对象名称'], visible: ['Visible', '可见'], hidden: ['Hidden', '隐藏'], locked: ['Locked', '已锁定'], unlocked: ['Unlocked', '未锁定'], hideObject: ['Hide {name}', '隐藏 {name}'], showObject: ['Show {name}', '显示 {name}'], lockObject: ['Lock {name}', '锁定 {name}'], unlockObject: ['Unlock {name}', '解锁 {name}'], lockHint: ['Unlock this object to transform or delete it.', '解锁此对象后可变换或删除。'], cameraVisibility: ['Hiding the camera hides its editor proxy; the preview stays active.', '隐藏摄影机仅隐藏编辑器中的替身，预览仍然有效。'],
  frameSelected: ['Frame Selected', '聚焦所选对象'], undo: ['Undo', '撤销'], redo: ['Redo', '重做'], resetLayout: ['Reset Layout', '重置布局'], restorePanel: ['Restore Panel', '还原面板'], maximizeHint: ['Double-click header to maximize or restore', '双击标题栏以最大化或还原'], resize: ['Resize {panel}', '调整{panel}大小'],
  framePosition: ['Frame Position', '画面位置'], screenX: ['Screen X', '画面 X'], screenY: ['Screen Y', '画面 Y'], width: ['Width', '宽度'], height: ['Height', '高度'], frameHint: ['Approximate bounds, before occlusion. Origin: top left. X → right, Y → down.', '遮挡前的近似包围框。左上角为原点，X 向右，Y 向下。'], outsideFrame: ['Outside camera frame', '位于画面外'], behindCamera: ['Behind camera', '位于摄影机后方'], nearCamera: ['Crosses camera near plane; bounds unavailable', '跨越摄影机近裁剪面，无法估算包围框'], noCamera: ['No storyboard camera', '无分镜摄影机'],
  descCamera: ['{camera} is {direction} {name}, {height}, approximately {distance} m away.', '{camera}位于{name}的{direction}，{height}，距离约 {distance} 米。'],
  eyeLevel: ['at eye level', '约为平视高度'], aboveEye: ['above eye level', '高于视线'], belowEye: ['below eye level', '低于视线'],
  front: ['in front of', '前方'], back: ['behind', '后方'], frontRight: ['front-right of', '右前方'], frontLeft: ['front-left of', '左前方'], backRight: ['back-right of', '右后方'], backLeft: ['back-left of', '左后方'], relativeRight: ['to the right of', '右侧'], relativeLeft: ['to the left of', '左侧'], overlapping: ['at the same position as', '同一位置'],
  descRelation: ['{name} is approximately {distance} meters {direction} {character}.', '{name}距{character}约 {distance} 米，位于其{direction}。'],
  descFrame: ['{name}: screen X {x}%, Y {y}%; {width}% wide × {height}% high.', '{name}：画面 X {x}%、Y {y}%；宽 {width}% × 高 {height}%。'],
  descFacing: ['{name} faces {direction}.', '{name}朝向{direction}。'], screenRight: ['screen right', '画面右侧'], screenLeft: ['screen left', '画面左侧'], towardCamera: ['the camera', '摄影机'], awayCamera: ['away from the camera', '摄影机反方向'],
  descOutside: ['{name}: outside the camera frame.', '{name}：位于摄影机画面外。'], descEmpty: ['The stage is empty. Add a character or prop to establish the blocking.', '场景为空。请添加角色或道具进行空间调度。'], descLens: ['{camera}: {fov}° vertical FOV, 16:9 frame.', '{camera}：垂直视场角 {fov}°，画幅 16:9。'],
} as const;
export type MessageKey = keyof typeof messages;
export function translate(language: Language, key: MessageKey, values: Record<string, string | number> = {}): string {
  return messages[key][language === 'zh' ? 1 : 0].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}
export const t = (key: MessageKey, values?: Record<string, string | number>) => translate(useSettings.getState().language, key, values);
export function useT() { const language = useSettings(s => s.language); return (key: MessageKey, values?: Record<string, string | number>) => translate(language, key, values); }
